on:
    workflow_dispatch: 
    push:
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for writing back to repo

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Source Code in Github Repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::295793222430:role/github-actions-terraform2
        aws-region: us-east-1

    - name: Run Terraform Init Command
      shell: pwsh
      run: terraform init

    - name: Run Terraform Plan Command
      shell: pwsh
      run: terraform plan

    - name: Run Terraform Apply Command
      shell: pwsh
      run: terraform apply -auto-approve

    - name: Commit Terraform State File
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Updating Terraform State File
        file_pattern: terraform.tfstate